version: "3.9"

services:
  acl-server:
    container_name: acl-server
    build:
      context: .
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/src
    depends_on:
      - postgres
    profiles:
      - servers
    networks:
      - acl-network

  postgres:
    container_name: acl-postgres
    image: postgres:13.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - acl-network

networks:
  acl-network:
    driver: bridge
    name: acl-network

volumes:
  postgres:
