version: "3.9"

services:
  acl-server:
    container_name: acl-server
    build:
      context: .
    restart: always
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 1 --timeout 180 core_server.wsgi"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    expose:
      - 8000
    volumes:
      - ${PWD}:/src
      - static_volume:/src/main/static
    depends_on:
      - postgres
    profiles:
      - nginx
      - servers
    networks:
      - acl-network

  nginx:
    image: nginx:latest
    container_name: acl-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/src/main/static
    networks:
      - acl-network

  postgres:
    container_name: acl-postgres
    image: postgres:13.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - acl-network

networks:
  acl-network:
    driver: bridge
    name: acl-network

volumes:
  postgres:
  static_volume:
