# Generated by Django 3.2.12 on 2022-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("reply_email", models.EmailField(max_length=254)),
                ("sender_ip", models.GenericIPAddressField()),
                ("sender_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Press",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(max_length=100)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("source", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Press",
            },
        ),
    ]
